### ISSUE TITLE
不好意思打搅啦！

### ISSUE THREAD

**Issue by chenhaishun** [codewithzichao/codewithzichao1.github.io#1]
您的博客内容非常详实，每次看完都受益匪浅。不过我今天发现您的博客网站在加载的时候出现404错误，是您更改地址了吗？还是一些别的什么原因呢？

**Comment by codewithzichao** [comment]
您好，非常感谢您关注我的博客。由于我在自己电脑上做某个项目的时候，不小心删除了blog所需要的某些依赖，导致崩溃，目前已经修好，可以正常访问。

**Comment by chenhaishun** [comment]
好的，谢谢您！
